"""The one shared testbench. References hold only the circuit; this module wraps it.

Conditions, library, supply, input sources, load, DC diagnostics and AC measurements are generated here from the
specs and from the circuit's own devices and nodes, so no reference repeats them and every topology is measured
in exactly the same way.
"""
from analog_agents.spice import circuit_nodes, logical_lines, mos_devices

PORTS = ('vdd', 'vinp', 'vinn', 'out')
RESERVED_PARAMS = ('VDD', 'VCM', 'CLOAD')
RESERVED_ELEMENTS = ('VSUPPLY', 'VINP', 'VINN', 'CLOAD_OUT')
FORBIDDEN_STATEMENTS = ('.lib', '.temp', '.control', '.endc', '.end', '.include')
PROPERTIES = ('id', 'gm', 'gds', 'vgs', 'vds', 'vth', 'vdsat')
LOOP_POLARITY = 'loop_real_lf'


def check_circuit(text):
    """A reference must be the circuit only, with the four testbench ports."""
    for line in logical_lines(text):
        first = line.split()[0]
        if first.lower() in FORBIDDEN_STATEMENTS:
            raise ValueError(f'{first} belongs to the shared testbench, not to a reference')
        if first.upper() in RESERVED_ELEMENTS:
            raise ValueError(f'{first} is generated by the shared testbench; remove it from the reference')
        if first.lower() == '.param' and line.split()[1].split('=')[0].upper() in RESERVED_PARAMS:
            raise ValueError(f'{line.split()[1]} is defined by the shared testbench (from the specs)')
    missing = [p for p in PORTS if p not in circuit_nodes(text)]
    if missing:
        raise ValueError('Circuit must use the testbench ports vdd, vinp, vinn, out; missing: ' + ', '.join(missing))


def number_text(value):
    return f'{value:.10g}'


def deck(circuit, specs, library, mode='full'):
    """Complete ngspice deck: DC operating point always, AC measurements only in `full` mode."""
    if mode not in ('dc', 'full'):
        raise ValueError('Unknown analysis mode')
    c, sweep = specs['conditions'], specs['ac_validation']['sweep']
    lines = [f'* op-amp testbench ({mode}): generated, not edited by hand',
             f'.lib "{library}" {specs["corner"]}', f'.temp {number_text(c["temperature_c"])}',
             f'.param VDD={number_text(c["vdd_v"])}', f'.param VCM={number_text(c["input_common_mode_v"])}',
             f'.param CLOAD={number_text(c["load_capacitance_f"])}', circuit.rstrip(),
             'VSUPPLY vdd 0 {VDD}', 'VINP vinp 0 DC {VCM} AC 0.5', 'VINN vinn 0 DC {VCM} AC -0.5',
             'CLOAD_OUT out 0 {CLOAD}',
             '.control', 'set noaskquit', 'set numdgt=10', 'op', 'echo DC_OPERATING_POINT']
    lines += [f'print v({node})' for node in circuit_nodes(circuit)]
    lines += ['let supply_current_a = -i(VSUPPLY)', 'let power_w = -i(VSUPPLY)*v(vdd)', 'print supply_current_a power_w']
    for device in mos_devices(circuit).values():
        lines += [f'print {device["diagnostic_prefix"]}[{p}]' for p in PROPERTIES]
    lines.append('echo END_DC_OPERATING_POINT')
    if mode == 'full':
        start = number_text(sweep['start_hz'])
        lines += [f'ac dec {sweep["points_per_decade"]} {start} {number_text(sweep["stop_hz"])}',
                  'let differential_input = v(vinp)-v(vinn)', 'let differential_gain = v(out)/differential_input',
                  'let loop_gain = -differential_gain', 'let gain = db(differential_gain)',
                  'let loop_phase_deg = 180/PI*cph(loop_gain)', 'let loop_real = real(loop_gain)',
                  f'meas ac {LOOP_POLARITY} FIND loop_real AT={start}', f'meas ac dc_gain_db FIND gain AT={start}',
                  'meas ac ugb_hz WHEN gain=0 FALL=1', 'meas ac phase_at_ugb FIND loop_phase_deg WHEN gain=0 FALL=1',
                  'let phase_margin_deg = 180+phase_at_ugb', 'print phase_margin_deg']
    lines += ['quit', '.endc', '.end']
    return '\n'.join(lines) + '\n'


def describe(specs):
    """The same facts as `deck`, in words, for the agents (single source: the specs and this module)."""
    c, s = specs['conditions'], specs['ac_validation']['sweep']
    return (f'Fixed shared testbench, generated by the toolchain and not part of the netlist: process {specs["process"]}, '
            f'corner {specs["corner"]}, {c["temperature_c"]} C. Supply {c["vdd_v"]} V on node vdd; inputs vinp and vinn at '
            f'{c["input_common_mode_v"]} V DC with differential AC (+0.5/-0.5); load {c["load_capacitance_f"]} F from out to ground. '
            f'DC: operating point of every MOS. AC sweep {s["start_hz"]:g}..{s["stop_hz"]:g} Hz. A = V(out)/(V(vinp)-V(vinn)); '
            f'loop L = -A (unity negative feedback to vinp); dc_gain_db = 20log10|A| at {s["start_hz"]:g} Hz; ugb_hz = first falling '
            '0 dB crossing; phase_margin_deg = 180 + phase(L) at that crossing (small-signal estimate, not a general stability proof); '
            'power_w = VDD * supply current. If L is not real and positive at low frequency the AC result is invalid.')
